In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping

In [5]:
import pandas as pd
import csv

# We use quoting=csv.QUOTE_NONE (or 3) to prevent pandas from expecting closing quotes
# inside text reviews, which fixes the EOF (End Of File) parsing error.
data = pd.read_csv("/content/IMDB Dataset.csv", quoting=csv.QUOTE_NONE, on_bad_lines='skip')

data

,,,,,,,,,,,,,,,,,,,,,,,,,,review,sentiment
"""One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right",as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence,which set in right from the word GO. Trust me,this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs,sex or violence. Its is hardcore,in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City,an experimental section of the prison where all the cells have glass fronts and face inwards,so privacy is not high on the agenda. Em City is home to many..Aryans,Muslims,gangstas,Latinos,Christians,Italians,Irish and more....so scuffles,death stares,dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences,forget charm,forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal,I couldn't say I was ready for it,but as I watched more,I developed a taste for Oz,and got accustomed to the high levels of graphic violence. Not just violence,but injustice (crooked guards who'll be sold out for a nickel,inmates who'll kill on order and get away with it,well mannered,middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz,you may become comfortable with what is uncom...,positive
"""A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting",and sometimes discomforting,"sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only """"has got all the polari"""" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries",not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which,rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses,"particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.""",positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""I thought this was a wonderful way to spend time on a too hot summer weekend",sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic,but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction,I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I'd laughed at one of Woody's comedies in years (dare I say a decade?). While I've never been impressed with Scarlet Johanson,"in this she managed to tone down her """"sexy"""" image and jumped right into a average",but spirited young woman.<br /><br />This may not be the crown jewel of his career,"but it was wittier than """"Devil Wears Prada"""" and more interesting than """"Superman"""" a great comedy to go see with friends.""",positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly",Jake decides to become Rambo and kill the zombie.<br /><br />OK,first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie,"and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.""",negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Petter Mattei's """"Love in the Time of Money"""" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money",power and success do to people in the different situations we encounter. <br /><br />This being a variation on the Arthur Schnitzler's play about the same theme,the director transfers the action to the present time New York where all these different characters meet and connect. Each one is connected in one way,or another to the next person,but no one seems to know the previous point of contact. Stylishly,the film has a sophisticated luxurious look. We are taken to see how these people live and the world they live in their own habitat.<br /><br />The only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. A big city is not exactly the best place in which human relations find sincere fulfillment,as one discerns is the case with most of the people we encounter.<br /><br />The acting is good under Mr. Mattei's direction. Steve Buscemi,Rosario Dawson,Carol Kane,Michael Imperioli,Adrian Grenier,and the rest of the talented cast,"make these characters come alive.<br /><br />We wish Mr. Mattei good luck and await anxiously for his next work.""",positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""I thought this movie did a down right good job. It wasn't as creative or original as the first",but who was expecting it to be. It was a whole lotta fun. the more i think about it the more i like it,and when it comes out on DVD I'm going to pay the money for it very proudly,every last cent. Sharon Stone is great,she always is,even if her movie is horrible(Catwoman),but this movie isn't,this is one of those movies that will be underrated for its lifetime,and it will probably become a classic in like 20 yrs. Don't wait for it to be a classic,watch it now and enjoy it. Don't expect a masterpiece,or something thats gripping and soul touching,just allow yourself to get out of your life and get yourself involved in theirs.<br /><br />All in all,this movie is entertaining and i recommend people who haven't seen it see it,because what the critics and box office say doesn't always count,see it for yourself,you never know,"you might just enjoy it. I tip my hat to this movie<br /><br />8/10""",positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Bad plot",bad dialogue,bad acting,idiotic directing,the annoying porn groove soundtrack that ran continually over the overacted script,and a crappy copy of the VHS cannot be redeemed by consuming liquor. Trust me,because I stuck this turkey out to the end. It was so pathetically bad all over that I had to figure it was a fourth-rate spoof of Springtime for Hitler.<br /><br />The girl who played Janis Joplin was the only faint spark of interest,and that was only because she could sing better than the original.<br /><br />If you want to watch something similar but a thousand times better,"then watch Beyond The Valley of The Dolls.""",negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""I am a Catholic taught in parochial elementary schools by nuns","taught by Jesuit priests in high school & college. I am still a practicing Catholic but would not be considered a """"good Catholic"""" in the church's eyes because I don't believe certain things or act certain ways just because the church tells me to.<br /><br />So back to the movie...its bad because two people are killed by this nun who is supposed to be a satire as the embodiment of a female religious figurehead. There is no comedy in that and the satire is not done well by the over acting of Diane Keaton. I never saw the play but if it was very different from this movies then it may be good.<br /><br />At first I thought the gun might be a fake and the first shooting all a plan by the female lead of the four former students as an attempt to demonstrate Sister Mary's emotional and intellectual bigotry of faith. But it turns out the bullets were real and the story has tragedy...the tragedy of loss of life (besides the two former students...the lives of the aborted babies",the life of the student's mom),the tragedy of dogmatic authority over love of people,the tragedy of organized religion replacing true faith in God. This is what is wrong with today's Islam,"and yesterday's Judaism and Christianity.""",negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""I'm going to have to disagree with the previous comment and side with Maltin on this one. This is a second rate","excessively vicious Western that creaks and groans trying to put across its central theme of the Wild West being tamed and kicked aside by the steady march of time. It would like to be in the tradition of """"Butch Cassidy and the Sundance Kid""""",but lacks that film's poignancy and charm. Andrew McLaglen's direction is limp,and the final 30 minutes or so are a real botch,with some incomprehensible strategy on the part of heroes Charlton Heston and Chris Mitchum. (Someone give me a holler if you can explain to me why they set that hillside on fire.) There was something callous about the whole treatment of the rape scene,and the woman's reaction afterwards certainly did not ring true. Coburn is plenty nasty as the half breed escaped convict out for revenge,but all of his fellow escapees are underdeveloped (they're like bowling pins to be knocked down one by one as the story lurches forward). Michael Parks gives one of his typically shifty,lethargic,mumbling performances,"but in this case it was appropriate as his modern style sheriff symbolizes the complacency that technological progress can bring about.""",negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""No one expects the Star Trek movies to be high art",but the fans do expect a movie that is as good as some of the best episodes. Unfortunately,this movie had a muddled,implausible plot that just left me cringing - this is by far the worst of the nine (so far) movies. Even the chance to watch the well known characters interact in another movie can't save this movie - including the goofy scenes with Kirk,Spock and McCoy at Yosemite.<br /><br />I would say this movie is not worth a rental,and hardly worth watching,however for the True Fan who needs to see all the movies,"renting this movie is about the only way you'll see it - even the cable channels avoid this movie.""",negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data = data.dropna()

In [7]:
texts = data["review"].astype(str)
texts

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right                                                               as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence  which set in right from the word GO. Trust me                                                                                                                                                                           this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs                                                                                                                       sex or violence. Its is hardcore                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City                                                                                                                                                                                                     an experimental section of the prison where all the cells have glass fronts and face inwards                                                                                                                                                                                                                                                                                                                                                                                                                                                                   so privacy is not high on the agenda. Em City is home to many..Aryans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Muslims                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gangstas                                                                                                                                       Latinos                                                                                                                                                                                                                                                 Christians                                                                                                                                                                                                                                                                                                                                                                                                                      Italians                                                                                                                                                                                                                                                                                                                                                                                                                       Irish and more....so scuffles                                                                                                death stares                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences  forget charm                                                                                                                                                                                                                                      forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal                                                                                              I couldn't say I was ready for it                                                                                                                                                                                                                                                                                                               but as I watched more                                                                                                                                                                                                                                                                                                 I developed a taste for Oz                                                                                                                                                                                          and got accustomed to the high levels of graphic violence. Not just violence                                                                                                                                                                                                                                                                                                                 but injustice (crooked guards who'll be sold out for a nickel                                                                                                                                                                 inmates who'll kill on order and get away with it                                                                                                                                                                                                                                                           well mannered                                                                                                                                                                                                                                                                                                                                                                           middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz     you may become comfortable with what is uncom...
"Gamers: DR is not a fancy made movie                                                                                                                                          it's more like amateur video. Horrible magic effect                                                                                                really fake fireball                                                                                                                                                                                                    terribly made dungeon                                                                                                                                                                                                     castle                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    village...... sword                                                                                                                                                                                                                                                                                                                                                              axe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shield                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             robe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       plate..... okok... everything. You will need about 10 minutes to adjust your expecting on visual                                               then you will get 105 minutes of fun.<br /><br />I'm from Hongkong and it's really hard to find RPers                                                                                                                                                   none of my friends play RPG and I always fancy to be one of the character in the world of D&D. Watching Gamers: DR just show me what would it be like to be a gamer. You see rule books                                                                                                                                                                                                                                         dices                                                                                                                                                                                                                                                                                                                                                                                                                          game set                                                                                                                     etc etc etc; You hear terms like ""fighter""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ""wizard""                                                                                                                                                                                                                           ""hit point""                                                                                                                                                                                                                                     ""level""                                                                                                                                                                                               ""character""                                                                                                                                                                                                                                                                                                                                   ""flaming hand""                                                                                                                                                                                                                                                                                                      ""Chaotic Evil"".<br /><br />What RPG fancy me is that it let you do anything u want to                                                                                                                             not bonded by software RPG. Gamers: DR provide the same element                                                                                                                                                                                                                                                                                                                              you wont know what happen next and it probably just make you laugh to dead. The movie goes both gamers's real life as well as in the D&D world. You will hear the gamer cast the dice when the character in game take action  which make you feel you really participle in the game.<br /><br />I don't want to spoil anything                                                                                                                                                                                                            but in short                                                                                                                                                                                                                                                                                                                                                                            Gamers: DR is a must watch movie for RPG lovers. For people never play RPG game                                                       I'm sure you still get many fun from it."

In [8]:
Sentiment = data["sentiment"]
Sentiment

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right                                                               as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence  which set in right from the word GO. Trust me                                                                                                                                                                           this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs                                                                                                                       sex or violence. Its is hardcore                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City                                                                                                                                                                                                     an experimental section of the prison where all the cells have glass fronts and face inwards                                                                                                                                                                                                                                                                                                                                                                                                                                                                   so privacy is not high on the agenda. Em City is home to many..Aryans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Muslims                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gangstas                                                                                                                                       Latinos                                                                                                                                                                                                                                                 Christians                                                                                                                                                                                                                                                                                                                                                                                                                      Italians                                                                                                                                                                                                                                                                                                                                                                                                                       Irish and more....so scuffles                                                                                                death stares                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences  forget charm                                                                                                                                                                                                                                      forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal                                                                                              I couldn't say I was ready for it                                                                                                                                                                                                                                                                                                               but as I watched more                                                                                                                                                                                                                                                                                                 I developed a taste for Oz                                                                                                                                                                                          and got accustomed to the high levels of graphic violence. Not just violence                                                                                                                                                                                                                                                                                                                 but injustice (crooked guards who'll be sold out for a nickel                                                                                                                                                                 inmates who'll kill on order and get away with it                                                                                                                                                                                                                                                           well mannered                                                                                                                                                                                                                                                                                                                                                                           middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz    positive
"Gamers: DR is not a fancy made movie                                                                                                                                          it's more like amateur video. Horrible magic effect                                                                                                really fake fireball                                                                                                                                                                                                    terribly made dungeon                                                                                                                                                                                                     castle                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    village...... sword                                                                                                                                                                                                                                                                                                                                                              axe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            shield                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             robe                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       plate..... okok... everything. You will need about 10 minutes to adjust your expecting on visual                                               then you will get 105 minutes of fun.<br /><br />I'm from Hongkong and it's really hard to find RPers                                                                                                                                                   none of my friends play RPG and I always fancy to be one of the character in the world of D&D. Watching Gamers: DR just show me what would it be like to be a gamer. You see rule books                                                                                                                                                                                                                                         dices                                                                                                                                                                                                                                                                                                                                                                                                                          game set                                                                                                                     etc etc etc; You hear terms like ""fighter""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ""wizard""                                                                                                                                                                                                                           ""hit point""                                                                                                                                                                                                                                     ""level""                                                                                                                                                                                               ""character""                                                                                                                                                                                                                                                                                                                                   ""flaming hand""                                                                                                                                                                                                                                                                                                      ""Chaotic Evil"".<br /><br />What RPG fancy me is that it let you do anything u want to                                                                                                                             not bonded by software RPG. Gamers: DR provide the same element                                                                                                                                                                                                                                                                                                                              you wont know what happen next and it probably just make you laugh to dead. The movie goes both gamers's real life as well as in the D&D world. You will hear the gamer cast the dice when the character in game take action  which make you feel you really participle in the game.<br /><br />I don't want to spoil anything                                                                                                                                                                                                            but in short                                                                                                                                                                                                                                                                                                                                                                            Gamers: DR is a must watch movie for RPG lovers. For people never play RPG game                                               positive

In [10]:
encoder = LabelEncoder()
labels = encoder.fit_transform(Sentiment)

print("Encoded labels:", labels)
print("Label mapping:", dict(zip(encoder.classes_, encoder.transform(encoder.classes_))))

Encoded labels: [1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0
 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0 0 1 0 1 1 0 1 1 1
 0 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0 0
 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1
 0 1 0 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 0 0 0 1 1
 0 1 0 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 1 0
 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1
 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 1 0 0 1
 1 0 0 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1 0 0 1
 1 0 0 1 0 0 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 0 1 1]
Label mapping: {'negative': np.int64(0), 'positive': np.int64(1)}

In [11]:
tokenizer = Tokenizer(
    lower=True,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(texts)

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Re-initialize and fit tokenizer since previous cell failed
tokenizer = Tokenizer(lower=True, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
sequences

[[20,
  100,
  243,
  594,
  28,
  42,
  9,
  595,
  244,
  245,
  45,
  20,
  39,
  61,
  11,
  596,
  28,
  37,
  597,
  187],
 [87, 131, 20, 101, 61, 74, 344, 29, 8],
 [25,
  598,
  102,
  5,
  34,
  345,
  599,
  20,
  11,
  2,
  346,
  5,
  103,
  61,
  2,
  115,
  246,
  132,
  347,
  7,
  150,
  104,
  247,
  4,
  37,
  46],
 [347, 600, 248, 7, 2, 88],
 [2,
  601,
  37,
  348,
  4,
  602,
  249,
  349,
  6,
  6,
  603,
  604,
  9,
  605,
  133,
  7,
  350,
  57,
  2,
  134,
  606,
  4,
  607,
  6,
  6,
  89,
  46,
  608,
  105,
  609,
  40,
  249,
  349,
  9,
  3,
  116,
  46,
  7,
  610,
  21,
  611,
  612,
  37,
  351,
  6,
  6,
  613,
  614,
  26,
  35,
  615,
  616,
  617,
  14,
  618,
  31,
  2,
  115,
  619,
  6,
  6,
  250,
  620,
  5,
  621,
  622,
  26,
  623,
  352,
  40,
  2,
  151,
  624],
 [5, 20, 34, 152, 3, 625],
 [43,
  26,
  62,
  38,
  75,
  5,
  626,
  188,
  627,
  628,
  2,
  353,
  5,
  629,
  4,
  35,
  630,
  63,
  16,
  32,
  189,
  12,
  106],
 [33, 188],
 [36, 25, 354],
 [87, 355],
 [35, 356, 15, 5, 87, 631, 36, 23, 251, 52, 357],
 [190, 632, 33, 5, 358, 252, 633, 135, 30, 6, 6, 103, 25, 117, 8],
 [13,
  10,
  27,
  634,
  136,
  153,
  253,
  81,
  5,
  9,
  101,
  2,
  53,
  635,
  21,
  636,
  359,
  637,
  638,
  360,
  5,
  361,
  2,
  639,
  640,
  4,
  641,
  11,
  2,
  362,
  15,
  642,
  13,
  8,
  191,
  57,
  643,
  363,
  4,
  105,
  644,
  14,
  89,
  645,
  646,
  2,
  362,
  647,
  4,
  2,
  648,
  64,
  17,
  5,
  87,
  105,
  3,
  364,
  254,
  28,
  13],
 [649],
 [2,
  365,
  48,
  192,
  23,
  16,
  3,
  150,
  14,
  2,
  46,
  118,
  154,
  365,
  366,
  8,
  11,
  650,
  24,
  651,
  8,
  18,
  3,
  255,
  7,
  652,
  155,
  14,
  256,
  14,
  90,
  20,
  107,
  7,
  16,
  653,
  7,
  3,
  244,
  4,
  654,
  367,
  64,
  24,
  2,
  368,
  655,
  369,
  656,
  16,
  37,
  137,
  657,
  13,
  10,
  244,
  156,
  69,
  658,
  20,
  62,
  31,
  33],
 [76, 659],
 [660, 40, 2, 661, 5, 662, 352, 663, 664, 665, 370, 119, 8, 3, 64],
 [12, 48, 119, 2, 193, 4, 42, 12, 194, 90, 12, 120, 195, 8, 6, 6, 136, 17],
 [5,
  666,
  52,
  14,
  667,
  257,
  668,
  54,
  669,
  670,
  671,
  30,
  4,
  17,
  45,
  2,
  371,
  121,
  258,
  672,
  372,
  673,
  2,
  674,
  6,
  6,
  675,
  676],
 [677, 19, 32, 4, 2, 91, 4, 2, 373, 678, 679],
 [5, 92, 3, 259, 196, 7, 197, 11, 10, 680, 260],
 [22, 10, 9, 3, 15, 13, 65, 134, 198, 16, 374, 136, 17, 6, 6, 681],
 [3, 15, 13, 682, 151, 70, 683, 74, 684, 39, 16, 685, 686],
 [22, 42, 3, 687],
 [688, 40, 689, 690, 375, 21, 2, 157, 691, 692],
 [5, 693, 8, 9, 62, 38, 49, 134],
 [694,
  695,
  158,
  159,
  54,
  92,
  8,
  696,
  82,
  697,
  199,
  2,
  698,
  699,
  376,
  19,
  200,
  201],
 [9, 3, 700, 377],
 [261, 701, 30, 7, 702],
 [55, 8, 25, 703, 3, 378, 704],
 [22, 87, 23, 131, 12, 705, 14, 8],
 [10,
  9,
  262,
  152,
  202,
  12,
  203,
  379,
  706,
  45,
  263,
  707,
  21,
  160,
  32,
  6,
  6,
  8,
  204,
  3,
  708,
  709,
  17,
  21,
  2,
  710,
  205,
  6,
  6,
  8,
  204,
  3,
  64,
  64,
  17,
  21,
  2,
  19,
  205,
  29,
  6,
  6,
  2,
  380],
 [71,
  39,
  711,
  13,
  122,
  161,
  123,
  30,
  43,
  14,
  2,
  712,
  264,
  21,
  124,
  713,
  2,
  265,
  4,
  151,
  39,
  162,
  14,
  3,
  714,
  715,
  4,
  716,
  717],
 [718, 3, 381, 206, 266],
 [28, 382, 7, 719, 21, 77, 49, 383, 10, 163, 9, 720, 15, 267, 31, 72, 721],
 [722,
  207,
  17,
  138,
  78,
  723,
  724,
  13,
  7,
  2,
  77,
  108,
  66,
  12,
  25,
  384,
  6,
  6,
  39,
  43,
  16,
  89,
  725,
  77,
  49,
  2,
  726,
  4,
  727,
  728,
  6,
  6],
 [18, 8, 27, 2, 120, 5, 8, 65, 34, 729, 2, 53, 88, 4, 730, 731, 5, 732, 733],
 [159, 7, 58, 103, 16, 268, 20, 164],
 [269,
  41,
  734,
  30,
  4,
  139,
  24,
  2,
  735,
  736,
  737,
  93,
  385,
  270,
  12,
  738,
  109,
  10,
  15,
  271,
  8,
  27,
  94,
  22,
  739,
  18,
  7,
  70,
  94,
  8,
  69,
  27],
 [12, 740, 20, 59, 150, 37, 46, 21, 10, 15, 5, 61, 2, 157],
 [59, 741, 104, 30, 4, 17],
 [31, 140, 742, 743, 386, 16, 95, 62, 4, 3, 150, 4, 37, 46],
 [5, 744, 745, 206, 266],
 [2, 387, 24, 2, 746, 54, 747, 36, 748, 202],
 [749,
  9,
  3,
  750,
  388,
  4,
  3,
  751,
  752,
  15,
  389,
  753,
  754,
  258,
  390,
  31,
  33,
  755,
  11,
  141,
  8,
  100,
  16,
  52,
  756,
  49,
  142],
 [25, 272, 59, 391, 2, 273, 392],
 [143, 4, 757, 758, 759, 760, 14, 761, 762],
 [110,
  60,
  763,
  764,
  11,
  2,
  120,
  393,
  88,
  2,
  208,
  11,
  2,
  765,
  766,
  31,
  2,
  111,
  9,
  767,
  768],
 [769, 770, 5, 10, 27, 38, 49, 394],
 [395, 396, 14, 2, 771, 209, 7, 58, 772],
 [20, 83, 58, 165, 125],
 [5, 3, 773, 774, 775, 124, 17],
 [22, 122, 96, 166, 776, 43, 6, 6, 210, 30, 4, 17],
 [5, 191, 6, 6, 8, 204, 3, 64, 210, 17, 29, 6, 6, 2, 380],
 [397, 11, 3, 398, 15, 28, 3, 399, 31, 72, 400, 64, 17],
 [61, 79, 199, 777, 5, 61, 778, 14, 2, 779, 124, 4, 780, 781, 66],
 [167, 13, 168, 3, 208, 782],
 [23, 3, 346, 7, 2, 783, 784, 785, 19, 401, 13, 11, 402, 5, 103, 16, 211],
 [397, 11, 3, 398, 15, 28, 3, 399, 31, 72, 400, 64, 17],
 [786,
  6,
  6,
  10,
  15,
  9,
  3,
  787,
  788,
  7,
  789,
  790,
  18,
  62,
  18,
  8,
  9,
  7,
  791,
  274,
  112,
  5,
  792,
  58,
  23,
  793,
  8,
  18,
  3,
  794,
  11,
  15,
  267,
  20,
  48,
  53,
  403,
  30,
  21,
  795,
  32,
  4,
  2,
  76,
  91,
  29,
  2,
  796,
  797,
  3,
  404,
  798,
  799],
 [800,
  801,
  4,
  802,
  9,
  35,
  803,
  405,
  275,
  4,
  15,
  22,
  2,
  804,
  21,
  3,
  805,
  806,
  807,
  212,
  213,
  808,
  11,
  2,
  809,
  4,
  810,
  811,
  812,
  11,
  406,
  214,
  49,
  2,
  813,
  4,
  407,
  24,
  2,
  814,
  815,
  4,
  816,
  817,
  818,
  819,
  212,
  389,
  820,
  821,
  822,
  4,
  215,
  823,
  824,
  825,
  74,
  408,
  5,
  826,
  35,
  827,
  4,
  32,
  275,
  24,
  160,
  828,
  2,
  15,
  28,
  3,
  829,
  830],
 [169, 151, 3, 831, 832],
 [36, 833, 29, 84, 7, 261, 834],
 [835, 7, 836, 73, 2, 166, 409, 4, 410, 837, 350],
 [18, 158, 54, 838, 10, 19, 7, 2, 111, 83, 411, 16, 276, 839],
 [412, 162, 8, 126, 840, 151, 277, 413, 278, 841, 29, 2, 842, 4, 3, 196, 108],
 [7, 279, 127, 42, 9, 44, 280, 843],
 [43,
  26,
  79,
  13,
  58,
  23,
  414,
  10,
  844,
  11,
  89,
  209,
  845,
  9,
  3,
  846,
  388,
  4,
  10,
  141],
 [5, 12, 117, 8, 10, 281, 216, 17, 17, 24, 108, 108, 110, 197, 2, 281],
 [847, 848],
 [5,
  415,
  95,
  354,
  7,
  16,
  849,
  850,
  6,
  6,
  851,
  37,
  139,
  12,
  39,
  53,
  106,
  10,
  15,
  18,
  3,
  852,
  853,
  6,
  6,
  64,
  30,
  4,
  17],
 [5, 217, 854, 4, 855, 856, 14, 38, 24, 857, 125, 14, 133, 4, 3, 376, 416],
 [858, 5, 859, 33, 31, 282],
 [5, 12, 59, 283, 417, 48, 142, 418, 860, 7, 861, 3, 862, 863],
 [41,
  864,
  122,
  3,
  419,
  420,
  865,
  218,
  75,
  5,
  866,
  2,
  420,
  9,
  218,
  75,
  26,
  84,
  6,
  6],
 [103, 170, 61, 270],
 [143, 4, 867, 421, 422, 868, 41, 869, 31, 2, 870, 871, 12, 423, 872, 18, 424],
 [873, 425, 425],
 [122,
  426,
  4,
  427,
  4,
  77,
  874,
  66,
  13,
  34,
  426,
  4,
  427,
  38,
  260,
  5,
  875,
  10,
  32,
  27,
  876,
  17,
  113,
  4,
  35,
  877,
  878,
  160,
  879,
  284,
  113],
 [24, 880, 14, 3, 428, 4, 217],
 [5, 881],
 [102,
  285,
  5,
  429,
  214,
  882,
  6,
  6,
  430,
  5,
  883,
  884,
  9,
  32,
  14,
  885,
  886,
  219,
  5,
  887,
  888,
  53],
 [286, 144, 26, 889, 188, 6, 6, 171],
 [5, 8, 27, 2, 890, 209, 7, 111, 2, 19, 8, 92, 67, 264, 431],
 [50,
  891,
  16,
  287,
  161,
  127,
  892,
  893,
  279,
  894,
  21,
  2,
  895,
  10,
  15,
  216,
  47,
  896,
  897,
  432,
  4,
  898,
  80],
 [12,
  59,
  128,
  70,
  70,
  10,
  83,
  16,
  899,
  132,
  900,
  2,
  901,
  902,
  12,
  172,
  433,
  903,
  34,
  7,
  119,
  80,
  904,
  14,
  434],
 [20, 48, 16, 288, 7, 97, 2, 905, 4, 2, 273, 173, 906, 7, 72, 289, 907],
 [41,
  290,
  291,
  2,
  174,
  5,
  435,
  109,
  3,
  436,
  5,
  437,
  438,
  28,
  439,
  5,
  220,
  440,
  441,
  8,
  63,
  16,
  442,
  7,
  2,
  443,
  7,
  444,
  2,
  445,
  221,
  22,
  2,
  446,
  5,
  292,
  11,
  56,
  41,
  175,
  447,
  26,
  289,
  448],
 [5,
  908,
  67,
  87,
  23,
  909,
  222,
  14,
  20,
  122,
  23,
  133,
  223,
  7,
  910,
  6,
  6,
  12,
  449,
  2,
  450,
  189,
  27,
  3,
  911,
  912,
  155,
  24,
  3,
  913,
  293,
  7,
  85,
  294,
  4,
  914,
  295,
  139,
  220,
  102,
  29,
  79,
  38,
  19],
 [915,
  153,
  253,
  6,
  6,
  367,
  7,
  916,
  176,
  5,
  224,
  917,
  7,
  451,
  2,
  273,
  392,
  4,
  452,
  453,
  20,
  176,
  2,
  115,
  275,
  454,
  13,
  452,
  9,
  279,
  176,
  40,
  918,
  5,
  2,
  919,
  4,
  2,
  15,
  2,
  19,
  920,
  7,
  16,
  921,
  22,
  145,
  25,
  35,
  922,
  7,
  923,
  80,
  36,
  924,
  5,
  455,
  925,
  926,
  5,
  57,
  125,
  2,
  456,
  5,
  927,
  457,
  40,
  177,
  11,
  8],
 [5, 13, 168, 458, 62],
 [55, 85, 131, 20, 418, 14, 10, 14, 928, 24, 929, 24, 930],
 [8,
  33,
  459,
  931,
  18,
  2,
  66,
  296,
  7,
  3,
  932,
  933,
  30,
  4,
  225,
  2,
  934,
  381,
  19,
  297,
  142,
  251],
 [2, 460, 298],
 [36,
  95,
  94,
  43,
  168,
  222,
  11,
  213,
  935,
  70,
  936,
  207,
  7,
  16,
  11,
  2,
  937,
  11,
  2,
  120,
  226,
  43,
  9,
  96,
  146,
  4,
  299,
  11,
  213,
  24,
  938,
  4,
  82,
  939,
  80,
  461,
  25,
  43,
  90,
  940,
  5,
  2,
  462,
  61,
  7,
  3,
  941,
  174,
  11,
  942],
 [22,
  943,
  944,
  945,
  946,
  300,
  82,
  62,
  52,
  947,
  948,
  12,
  172,
  227,
  25,
  114,
  3,
  38,
  949],
 [463,
  23,
  464,
  6,
  6,
  8,
  27,
  86,
  55,
  465,
  466,
  118,
  7,
  301,
  10,
  6,
  6,
  17,
  30,
  4,
  17,
  302],
 [5, 2, 351, 250, 950, 4, 951, 43, 26, 79, 952, 13, 467, 16, 468, 22, 53, 374],
 [303,
  469,
  953,
  2,
  147,
  296,
  30,
  178,
  954,
  8,
  30,
  177,
  159,
  65,
  225,
  110,
  60,
  161,
  159],
 [41, 175, 101, 21, 2, 470, 4, 93, 281],
 [13, 9],
 [108,
  471,
  955,
  956,
  19,
  957,
  4,
  958,
  959,
  9,
  960,
  31,
  36,
  261,
  91,
  472,
  372,
  5,
  961,
  155,
  248,
  9,
  42,
  8,
  473,
  5,
  962,
  9,
  963,
  49,
  474,
  2,
  228,
  9,
  81],
 [3,
  964,
  54,
  304,
  3,
  211,
  965,
  966,
  11,
  2,
  967,
  968,
  475,
  276,
  969,
  970,
  9,
  35,
  30,
  4,
  971,
  972,
  276,
  476,
  477,
  973,
  6,
  6,
  3,
  179,
  4,
  2,
  144,
  11,
  10,
  19,
  26,
  25,
  478,
  30,
  12,
  148,
  974,
  7,
  975,
  2,
  976,
  361,
  7,
  10,
  19,
  48,
  353,
  18,
  46,
  305,
  21,
  5,
  129,
  977,
  978,
  11,
  93,
  979],
 [18,
  11,
  980,
  981,
  982,
  31,
  2,
  111,
  8,
  9,
  33,
  44,
  229,
  32,
  467,
  379,
  22,
  105,
  983,
  31,
  8,
  8,
  27,
  23,
  44,
  479,
  480,
  8,
  27,
  44,
  229],
 [984, 985, 78, 78],
 [58, 44, 40, 33, 986],
 [481],
 [5, 50, 9, 73, 2, 53, 189, 11, 8, 13, 306],
 [987, 6, 6, 17, 17],
 [227, 194, 47, 307, 4, 104, 27, 988, 254],
 [25, 3, 989, 21, 990, 991, 6, 6, 23, 21, 47, 60, 180, 482],
 [992,
  993,
  2,
  364,
  130,
  2,
  994,
  995,
  216,
  8,
  996,
  70,
  2,
  308,
  164,
  483,
  484,
  7,
  61,
  11,
  13,
  257,
  90,
  485,
  113,
  253,
  50,
  27,
  11,
  82,
  997,
  998,
  8,
  27,
  25,
  3,
  486,
  190,
  56,
  100,
  999,
  2,
  1000,
  1001,
  22,
  9,
  25,
  160,
  1002,
  4,
  1003,
  56,
  1004,
  7,
  2,
  1005,
  13,
  9,
  10,
  15,
  72,
  11,
  141,
  13,
  230,
  56,
  309,
  8,
  33,
  14,
  67,
  11,
  13,
  8,
  27,
  486,
  3,
  179,
  51,
  10,
  15],
 [22, 411, 3, 1006, 11, 2, 1007, 13, 9, 1008, 295, 487],
 [2, 91, 4, 167, 48, 52, 49, 1009, 20],
 [29,
  1010,
  1011,
  1012,
  488,
  1013,
  2,
  1014,
  1015,
  1016,
  149,
  1017,
  92,
  25,
  1018,
  1019,
  29,
  35,
  250,
  266,
  270,
  109,
  2,
  1020,
  1021,
  181,
  1022,
  1023,
  1024,
  114,
  1025,
  1026,
  8,
  7,
  2,
  1027,
  1028,
  21,
  2,
  77,
  187,
  4,
  93,
  1029,
  489,
  9,
  489],
 [10, 15, 9, 192, 86, 2, 416, 97, 8, 28, 3, 1030, 20, 117],
 [1031, 5, 429, 102, 2, 470],
 [5, 1032, 7, 3, 490],
 [1033, 155, 1034, 1035, 1036],
 [1037, 1038, 16, 491, 30, 21, 152, 3, 1039, 1040],
 [310, 2, 15, 267, 2, 1041, 54, 128, 42, 263, 287, 6, 6, 78, 17],
 [5,
  87,
  492,
  311,
  2,
  1042,
  1043,
  1044,
  13,
  9,
  1045,
  7,
  312,
  493,
  1046,
  10,
  32,
  30,
  45,
  20,
  34,
  2,
  1047,
  14,
  8,
  124,
  108,
  17],
 [28,
  3,
  229,
  313,
  5,
  111,
  33,
  218,
  1048,
  1049,
  21,
  2,
  385,
  5,
  2,
  494,
  1050,
  1051,
  28,
  123,
  112,
  6,
  6,
  134,
  144,
  203,
  1052,
  28,
  3,
  117,
  88,
  13,
  9,
  126,
  314,
  495,
  1053,
  4,
  2,
  286,
  495,
  1054],
 [8, 473, 7, 67, 13, 359, 1055, 1056, 1057, 13],
 [10, 32, 126, 1058, 7, 2, 76, 91, 6, 6, 1059, 1060, 17, 17],
 [59, 1061, 10, 19, 124, 17],
 [5, 36, 47, 1062, 162, 13, 43, 9, 3, 1063, 228, 14, 135],
 [496, 497],
 [57, 45, 20, 498, 3, 1064, 4, 1065, 1066, 6, 6, 1067],
 [1068, 9, 1069, 9, 35, 1070, 428, 4, 231, 13, 48, 1071, 1072, 1073],
 [499, 1074],
 [500, 1075, 78, 1076, 1077, 500, 407, 1078, 1079, 1080, 1081],
 [71, 39, 1082, 1083, 13, 41, 26, 23, 2, 1084, 54, 65, 16, 1085, 315],
 [501, 50, 502, 2, 1086, 1087, 39, 401, 10, 29, 105, 3, 1088, 1089, 15],
 [45, 20, 150, 37, 139, 21, 3, 1090, 24, 255],
 [145, 127],
 [22,
  20,
  39,
  1091,
  316,
  2,
  1092,
  317,
  20,
  107,
  7,
  1093,
  37,
  1094,
  24,
  228,
  1095,
  4,
  116,
  1096,
  1097,
  75,
  51,
  1098,
  4,
  2,
  1099,
  5,
  1100,
  1101,
  58,
  23,
  97,
  1102,
  1103,
  12,
  63,
  34,
  214,
  118,
  47,
  46,
  1104],
 [87, 1105, 1106, 1107, 1108, 1109, 48, 97, 70, 13, 306, 30],
 [58,
  503,
  46,
  30,
  14,
  10,
  43,
  26,
  66,
  56,
  85,
  3,
  179,
  4,
  139,
  5,
  43,
  26,
  66,
  56,
  85,
  318,
  12,
  63,
  89,
  232,
  1110,
  2,
  504],
 [22,
  12,
  126,
  51,
  1111,
  474,
  505,
  1112,
  12,
  148,
  1113,
  311,
  2,
  506,
  4,
  2,
  319,
  1114,
  182,
  21,
  147],
 [183, 227, 25, 191, 127, 14, 10, 196],
 [2,
  15,
  1115,
  1116,
  1117,
  212,
  183,
  32,
  9,
  101,
  288,
  7,
  1118,
  130,
  32,
  507,
  1119,
  5,
  160,
  1120],
 [10, 15, 9, 184, 94, 5, 23, 1121, 1122, 6, 6, 47, 193, 1123],
 [8, 9, 320, 247, 4, 508, 217, 56, 12, 509, 106],
 [56,
  305,
  7,
  169,
  20,
  70,
  1124,
  5,
  348,
  39,
  197,
  1125,
  28,
  63,
  16,
  1126,
  1127,
  6,
  6,
  86,
  510,
  282,
  14,
  511,
  321,
  1128,
  5,
  1129,
  5,
  7,
  60,
  1130,
  1131,
  1132,
  512,
  11,
  3,
  1133,
  13,
  9,
  1134,
  299],
 [119,
  67,
  161,
  222,
  43,
  26,
  513,
  38,
  1135,
  514,
  1136,
  66,
  7,
  1137,
  1138,
  52,
  51,
  2,
  1139,
  67,
  4,
  2,
  1140],
 [2,
  1141,
  223,
  11,
  74,
  515,
  9,
  516,
  7,
  249,
  3,
  116,
  1142,
  15,
  1143,
  36,
  319,
  70,
  1144,
  5,
  321,
  1145,
  39,
  58,
  44,
  62],
 [86, 517, 1146, 9, 2, 1147, 1148, 1149, 518, 378, 46, 1150, 1151],
 [126,
  18,
  11,
  519,
  22,
  31,
  140,
  274,
  520,
  128,
  90,
  7,
  521,
  2,
  1152,
  1153,
  1154,
  21,
  522,
  14,
  1155,
  113,
  57,
  183,
  50,
  9,
  81,
  132,
  3,
  523,
  71,
  519,
  59,
  34,
  422,
  520,
  522,
  28,
  1156,
  1157,
  1158,
  58,
  71],
 [1159,
  11,
  1160,
  130,
  1161,
  1162,
  1163,
  3,
  1164,
  1165,
  1166,
  56,
  1167,
  3,
  179,
  7,
  1168],
 [370, 1169, 7, 2, 1170, 11, 47, 1171, 29, 10, 174, 21, 6, 6, 104, 17],
 [10,
  9,
  524,
  113,
  4,
  47,
  112,
  13,
  12,
  83,
  34,
  118,
  52,
  1172,
  40,
  1173,
  47,
  1174,
  1175,
  1176],
 [5,
  12,
  106,
  8,
  12,
  25,
  525,
  13,
  72,
  117,
  88,
  183,
  3,
  1177,
  223,
  174,
  9,
  3,
  137,
  52,
  1178,
  49,
  8,
  526,
  7,
  16,
  5,
  33,
  2,
  322,
  188,
  8,
  27,
  42,
  69,
  1179],
 [5,
  18,
  233,
  8,
  92,
  2,
  1180,
  1181,
  4,
  1182,
  2,
  15,
  1183,
  4,
  377,
  18,
  233,
  8,
  9,
  98,
  86,
  154,
  22,
  23,
  18,
  3,
  1184,
  21,
  1185,
  1186,
  260,
  24,
  82,
  1187,
  1188],
 [24,
  31,
  140,
  18,
  18,
  202,
  18,
  3,
  19,
  73,
  454,
  5,
  1189,
  39,
  16,
  6,
  6,
  193,
  323],
 [5, 36, 501, 1190, 502, 1191],
 [324, 1192, 24, 1193, 223, 1194, 6, 6, 527, 182],
 [1195,
  7,
  3,
  17,
  90,
  1196,
  7,
  2,
  371,
  205,
  12,
  200,
  106,
  10,
  15,
  14,
  33,
  1197],
 [22,
  36,
  198,
  1198,
  133,
  7,
  1199,
  18,
  3,
  1200,
  1201,
  1202,
  4,
  1203,
  1204,
  528,
  1205],
 [2, 1206, 252, 1207, 135, 33, 7, 308],
 [12, 39, 69, 106, 8],
 [90, 8, 99, 44, 529, 34, 1208, 3, 1209],
 [526, 7, 97, 10, 19],
 [23,
  95,
  94,
  45,
  20,
  39,
  185,
  3,
  530,
  264,
  1210,
  24,
  366,
  8,
  21,
  490,
  477,
  14,
  1211],
 [5,
  1212,
  10,
  1213,
  71,
  451,
  29,
  32,
  232,
  7,
  2,
  493,
  1214,
  144,
  18,
  1215,
  1216,
  1217,
  2,
  141,
  13,
  325,
  9,
  2,
  450,
  531,
  4,
  532,
  40,
  158,
  54,
  1218,
  8,
  163,
  5,
  71,
  83,
  433,
  61,
  79,
  1219,
  322,
  3,
  531,
  4,
  533,
  11,
  533,
  11,
  325],
 [5, 36, 69, 1220, 2, 1221, 4, 1222, 11, 534, 7, 123, 1223],
 [1224, 9, 38, 49, 1225, 22, 23, 18, 84, 18, 1226],
 [24,
  45,
  20,
  39,
  25,
  358,
  316,
  110,
  171,
  3,
  137,
  1227,
  25,
  51,
  50,
  1228,
  11,
  2,
  19,
  55,
  20,
  39,
  171,
  10,
  19,
  14,
  42,
  8,
  9,
  12,
  128,
  12,
  58,
  535,
  46,
  6,
  6],
 [1229, 1230],
 [18, 12, 27, 6, 6, 47, 121, 136, 17, 6, 6, 326, 1231, 1232, 14, 1233, 1234],
 [1235, 113, 4, 327, 536, 1236, 190, 20, 518, 2, 469],
 [81, 11, 2, 537, 4, 82, 1237, 1238, 234, 15],
 [300,
  89,
  84,
  1239,
  13,
  475,
  100,
  34,
  11,
  287,
  44,
  8,
  1240,
  111,
  2,
  1241,
  1242,
  1243,
  1244,
  7,
  32,
  4,
  2,
  1245,
  1246,
  11,
  1247,
  146,
  10,
  15,
  1248,
  42,
  53,
  3,
  235,
  75,
  34,
  142,
  1249,
  8,
  9,
  23,
  53,
  35,
  538,
  1250,
  4,
  146,
  22,
  8,
  126,
  243,
  3,
  539,
  11,
  13,
  1251,
  146],
 [11, 538, 323, 1252],
 [74,
  4,
  56,
  26,
  76,
  84,
  234,
  1253,
  31,
  236,
  540,
  100,
  16,
  32,
  14,
  144,
  54,
  1254,
  31,
  2,
  481,
  1255,
  64,
  17],
 [2, 237, 19, 142, 304, 12, 1256, 1257, 10, 19, 21, 47, 237, 1258],
 [541, 25, 1259, 10, 15, 170, 1260],
 [11,
  1261,
  14,
  112,
  6,
  6,
  1262,
  1263,
  27,
  2,
  1264,
  4,
  1265,
  542,
  75,
  4,
  2,
  1266,
  1267,
  21,
  2,
  1268,
  9,
  96,
  1269,
  78,
  104],
 [14,
  1270,
  82,
  1271,
  1272,
  13,
  50,
  1273,
  27,
  2,
  1274,
  1275,
  4,
  5,
  14,
  1276,
  7,
  58,
  13,
  41,
  175,
  7,
  1277,
  28,
  93,
  318],
 [47, 523, 63, 1278, 45, 12, 195, 222, 125, 49, 10],
 [16,
  76,
  355,
  6,
  6,
  1279,
  20,
  99,
  1280,
  13,
  79,
  1281,
  11,
  10,
  15,
  26,
  29,
  77,
  543,
  544,
  66,
  12,
  148,
  545,
  2,
  1282,
  1283,
  1284,
  328,
  27,
  1285,
  29,
  1286,
  68,
  2,
  1287,
  1288,
  22,
  12,
  126,
  195,
  3,
  546,
  77,
  329,
  13,
  12,
  1289,
  26,
  29,
  77,
  75,
  42,
  3,
  1290,
  293],
 [10, 19, 92, 96, 1291, 547],
 [382, 102, 17, 63, 16, 1292, 28, 10],
 [548, 1293, 21, 11, 2, 66],
 [1294, 1295, 9, 184, 549, 6, 6],
 [8, 25, 305, 7, 169, 13, 50, 453, 224, 96, 194, 109, 129, 1296, 1297, 1298],
 [1299, 153, 29, 81, 18, 1300, 18, 41, 312],
 [57, 14, 1301, 1302, 51, 10, 6, 6, 1303, 1304, 65, 16, 315],
 [5, 187, 40, 187, 129, 26, 262, 38, 66, 49, 41, 114, 7, 16, 6, 6, 138, 17],
 [54,
  550,
  7,
  1305,
  29,
  123,
  1306,
  7,
  1307,
  551,
  114,
  7,
  330,
  28,
  14,
  153,
  2,
  141,
  13,
  50,
  282,
  1308,
  35,
  331,
  182,
  7,
  2,
  1309,
  1310,
  71,
  175,
  468,
  33,
  10,
  127,
  31,
  2,
  552,
  4,
  2,
  19,
  238,
  271,
  13,
  551,
  1311,
  27,
  331,
  4,
  2,
  1312,
  13,
  461,
  1313,
  28,
  5,
  23,
  271,
  14,
  131,
  45,
  1314,
  16,
  1315,
  331,
  4,
  8,
  11,
  3,
  1316,
  4,
  1317,
  63,
  50,
  107,
  7,
  85,
  2,
  115,
  456,
  1318,
  180,
  12,
  39,
  529,
  97,
  10,
  1319,
  11,
  166,
  112,
  238,
  23,
  55,
  11,
  2,
  66],
 [45,
  41,
  26,
  11,
  2,
  1320,
  14,
  161,
  405,
  49,
  2,
  1321,
  332,
  1322,
  59,
  60,
  45,
  45,
  20,
  107,
  455,
  521,
  1323,
  24,
  1324,
  553,

In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 200

X = pad_sequences(
    sequences,
    maxlen=max_len,
    padding='post'
)

X

array([[ 20, 100, 243, ...,   0,   0,   0],
       [ 87, 131,  20, ...,   0,   0,   0],
       [ 25, 598, 102, ...,   0,   0,   0],
       ...,
       [ 96, 572,   2, ...,   0,   0,   0],
       [ 55,  41, 100, ...,   0,   0,   0],
       [ 56,   9,  23, ...,   0,   0,   0]], dtype=int32)

In [14]:
y = np.array(labels)
y

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [16]:
vocab_size = len(tokenizer.word_index) + 1

print("Vocabulary size:", vocab_size)

Vocabulary size: 1881

In [17]:
model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=max_len
    )
)

model.add(
    Bidirectional(
        LSTM(
            128,
            dropout=0.3,
            recurrent_dropout=0.3
        )
    )
)

model.add(Dropout(0.3))

model.add(
    Dense(
        128,
        activation='relu'
    )
)

model.add(Dropout(0.3))

model.add(
    Dense(
        len(set(labels)),
        activation='softmax'
    )
)

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [18]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [19]:
early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=3,
    restore_best_weights=True
)

In [20]:
model.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=64,
    validation_data=(X_test, y_test),
    callbacks=[early_stop]
)

Epoch 1/15
5/5 ━━━━━━━━━━━━━━━━━━━━ 14s 1s/step - accuracy: 0.4667 - loss: 0.6953 - val_accuracy: 0.5278 - val_loss: 0.6912
Epoch 2/15
5/5 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - accuracy: 0.5439 - loss: 0.6893 - val_accuracy: 0.5278 - val_loss: 0.6911
Epoch 3/15
5/5 ━━━━━━━━━━━━━━━━━━━━ 6s 1s/step - accuracy: 0.5368 - loss: 0.6915 - val_accuracy: 0.5278 - val_loss: 0.6903
Epoch 4/15
5/5 ━━━━━━━━━━━━━━━━━━━━ 10s 1s/step - accuracy: 0.5333 - loss: 0.6808 - val_accuracy: 0.5278 - val_loss: 0.6892

In [21]:
loss, accuracy = model.evaluate(X_test, y_test)

print("\nAccuracy :", accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 242ms/step - accuracy: 0.5278 - loss: 0.6912

Accuracy : 0.5277777910232544

In [25]:
def detect_sentiment(sentence):
    sentence = sentence.lower()
    seq = tokenizer.texts_to_sequences([sentence])
    seq = pad_sequences(
        seq,
        maxlen=max_len,
        padding='post',
        truncating='post'
    )

    # The model outputs a probability distribution over classes because of activation='softmax'
    prediction = model.predict(seq, verbose=0)[0]

    # Find the index with the highest probability
    predicted_index = np.argmax(prediction)
    confidence = prediction[predicted_index] * 100

    sentiment = encoder.inverse_transform([predicted_index])[0]

    return sentiment, confidence

In [26]:
review = "This movie was amazing and the acting was excellent!"

sentiment, confidence = detect_sentiment(review)

print("Sentiment:", sentiment)
print(f"Confidence: {confidence:.2f}%")

Sentiment: positive
Confidence: 52.93%